Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # NFS Server
  config.vm.define "nfs-server" do |server|
    server.vm.hostname = "nfs-server"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    # Six extra disks for the server
    (1..6).each do |i|
      server.vm.disk :disk, size: "2GB", name: "server-disk-#{i}"
    end

    server.vm.provision "shell", inline: <<-SHELL
      set -eux
      apt-get update -y
      apt-get install -y nfs-kernel-server
    SHELL
  end

  # NFS Client
  config.vm.define "nfs-client" do |client|
    client.vm.hostname = "nfs-client"
    client.vm.network "private_network", ip: "192.168.56.20"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
    end

    # Two extra disks for the client
    (1..2).each do |i|
      client.vm.disk :disk, size: "2GB", name: "client-disk-#{i}"
    end

    client.vm.provision "shell", inline: <<-SHELL
      set -eux
      apt-get update -y
      apt-get install -y nfs-common autofs
    SHELL
  end
end